name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main
      - staging
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./app/
          server-dir: public_html/app/
          exclude: |
            **/.git*
            **/.git*/**
            config/db.php
            upload/**
            justificatifs/**
            vendor/chart.js/**
            **/*.sql
            **/*.log
            **/error_log
